### ISSUE TITLE
All PHPUnit assertions involving DateTime comparison fail with PHP 7.1

### ISSUE THREAD

**Issue by asprega** [hnw/php-timecop#14]
Most likely due to the "microseconds change" in PHP7.1 (http://php.net/manual/en/migration71.incompatible.php) all tests involving dates mocked using timecop now fail because they do not take microseconds into account. This is a very simple test case that passes in PHP7.0 but fails in PHP7.1 (I'm using PHPUnit 5.7):

```
    public function test_timecop()
    {
        $now = new \DateTime();
        timecop_freeze($now->getTimestamp());

        $this->assertEquals(new \DateTime(), $now);
    }
```

and the output:
```
Failed asserting that two DateTime objects are equal.
Expected :2016-12-23T10:33:58.528377+0100
Actual   :2016-12-23T10:33:58.528332+0100
```

Should the `timecop_freeze` signature be modified to allow "freezing" microseconds as well? Things that I can think of are either using a float (but maybe it's risky?) or a DateTime instance directly, which would also make freezing easier IMHO.

**Comment by asprega** [comment]
@hnw any ideas?

**Comment by hnw** [comment]
Thank you for reporting this issue.

Surely this seems to be a problem to be fixed. I think that it is a good idea to let `timecop_freeze()` receive `DateTime` as 1st argument.

On the other hand, the example test code in your report is too simplified, so your real problem seems to be obscured from me. In the case of this test, you can solve your trouble by doing `clone $now`. If possible, would you tell me a bit more accurate test code?

In additon, I noticed another problem. The current implementation of `timecop_freeze()` cannot freeze time at the current time. In other words, `timecop_freeze(time())` has no effects. `timecop_freeze(time() - 1)` might be a workaround.

**Comment by asprega** [comment]
Thanks for your reply.

Sure, here's one more practical example. I have a `CustomerInvoice` that can be voided. When it is, it stores the current date in one of its properties like this:

```
    class CustomerInvoice
    {
        public function void()
        {
            $this->voidDate = new \DateTime();
        }
    }
```

So in order to verify that behavior in a unit test, in PHP 7.0 I'd do this:

```
    public function test_invoice_void()
    {
        $now = new \DateTime();
        timecop_freeze($now->getTimestamp());

        $invoice = new CustomerInvoice();
        $invoice->void();

        $this->assertEquals($now, $invoice->getVoidDate());
    }
```

But it is now fails because microseconds do not match.

As for the latter problem, I never noticed that. I always used to freeze with `$now->getTimeStamp()`, never with `time()` directly. I guess maybe that's why.

**Comment by asprega** [comment]
@hnw sorry to bother you again, just wanted to know whether you think I should provide more info. Do you need any help in fixing that? I would've done that but as this probably involves a major BC break I assumed you wanted to handle it.

**Comment by hnw** [comment]
Hi. Now `timecop_freeze()` and `timecop_travel()` accepts either `DateTimeInterface` or `int` on php-timecop v1.2.0. Please try it.

See also [tests/issue_014.phpt](https://github.com/hnw/php-timecop/blob/master/tests/issue_014.phpt).
