### ISSUE TITLE
Issue when compiling in osx

### ISSUE THREAD

**Issue by RopoMen** [hnw/php-timecop#23]
Hi,

I'm using PHP 5.6.30 and I wanted to build php-timecop using guide provided in README.md, I encountered following issue

```bash
make install
Installing shared extensions:     /usr/lib/php/extensions/no-debug-non-zts-20131226/
cp: /usr/lib/php/extensions/no-debug-non-zts-20131226/#INST@10032#: Operation not permitted
make: *** [install-modules] Error 1
```

using "sudo make install" does not solve the issue.

Then I installed php-timecop through `brew`, but it installed php71 as a dependency and now my unit tests are using php71 and fails.

Why the timecop build fails?

also, I needed to install autoconf to be able to run configuration.
```bash
brew install autoconf
```

macOS Sierra, version 10.12.5

**Comment by hnw** [comment]
At first, stock PHP's problem is because of the macOS's specification.

From El Captitan (10.11), we can't write to `/usr` or `/bin` even if we have root permission. See [File System Protections](https://developer.apple.com/library/content/documentation/Security/Conceptual/System_Integrity_Protection_Guide/FileSystemProtections/FileSystemProtections.html) for details.

So, If you want to use php-timecop with stock PHP on Sierra, you should change `extension_dir` settings to writable path.

I think using `brew` might be easier. Try `brew install php56-timecop` .

**Comment by RopoMen** [comment]
Hi,

ty, I think this should be added in to readme guide as well.
```bash
brew install homebrew/php/php56-timecop
```

hah, you edited that readme a day a go :) I remembered that it wasn't there before when I last time checked it, about two weeks ago.
